name: bloc_signals_test
resolution: workspace
description: Declarative unit testing utilities for BlocSignal and CubitSignal.
version: 0.1.1
repository: https://github.com/RandalSchwartz/BlocSignal
issue_tracker: https://github.com/RandalSchwartz/BlocSignal/issues

topics:
  - testing
  - unit-testing
  - bloc
  - signals

environment:
  sdk: ^3.5.0

dependencies:
  bloc_signals: ^0.2.1
  meta: ">=1.11.0 <2.0.0"
  test: ^1.25.6

dev_dependencies:
  coverage: ^1.11.0
  very_good_analysis: ^10.1.0
