name: bloc_signals_workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - bloc_signals
  - bloc_signals_flutter
  - bloc_signals_flutter/example
  - bloc_signals_otel
  - bloc_signals_test
  - bloc_signals_lint
  - bloc_signals_riverpod
  - bloc_signals_hydrate
  - bloc_signals_devtools
  - benchmarks
  - examples/shopping_cart
  - examples/auth_flow
  - examples/infinite_scroll

dev_dependencies:
  test: ^1.25.6
