name: bloc_signals_workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - bloc_signals
  - bloc_signals_flutter
  - bloc_signals_flutter/example
  - otel_bloc_signals
  - bloc_signals_test
  - bloc_signals_lint


