name: bloc_signals_workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - bloc_signals
  - bloc_signals_flutter
  - bloc_signals_flutter/example
  - bloc_signals_otel
  - bloc_signals_test
  - bloc_signals_lint
  - bloc_signals_riverpod
  - bloc_signals_hydrate
  - bloc_signals_devtools
  - benchmarks
  - examples/shopping_cart
  - examples/auth_flow
  - examples/infinite_scroll
  - examples/flutter_counter
  - examples/flutter_async
  - examples/flutter_colorband
  - examples/eval_calculator
  - examples/persist_shared_preferences
  - examples/clean_architecture
  - examples/get_it_signals
  - examples/flutter_timer
  - examples/flutter_todos
  - examples/flutter_weather
  - examples/flutter_dynamic_form
  - examples/flutter_wizard
  - examples/flutter_form_validation
  - examples/bloc_concurrency_visualizer
  - examples/github_search
  - examples/flutter_complex_list
  - examples/flutter_bloc_with_stream
  - website

dev_dependencies:
  test: ^1.25.6
