name: flutter_async_example
description: Async state handling example with CubitSignal.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_signals: ^1.0.0
  bloc_signals_flutter: ^1.0.0
  signals_core: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
