name: bloc_signals_flutter
resolution: workspace
description: Flutter extensions and bindings for BlocSignal state management library.
version: 0.2.4
repository: https://github.com/RandalSchwartz/BlocSignal
issue_tracker: https://github.com/RandalSchwartz/BlocSignal/issues

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  bloc_signals: ^0.2.0
  flutter:
    sdk: flutter
  signals_flutter: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
